networks:
   jenkins:
      driver: bridge
volumes:
   jenkins-data:
      driver: local
   jenkins-docker-certs:
      driver: local
services:
   jenkins_dotnet:
      build: ./jenkins_dotnet
      networks: 
         - jenkins
      ports:
         - "${JENKINS_WEB_PORT}:8080"
         - "${JENKINS_MASTER_PORT}:50000"
      volumes:
         - jenkins-data:/var/jenkins_home
         - jenkins-docker-certs:/certs/client
         - ${REPORTS_PATH}:/var/jenkins_home/allure
   nginx:
      build: ./nginx
      ports:
         - "${NGINX_PORT}:80"
      volumes:
         - ${REPORTS_PATH}:/usr/share/nginx/html
         - ./nginx/my_config:/etc/nginx/my_config